const RESOLUTIONS = {
  '16:9': { '720p': [1280, 720], '1080p': [1920, 1080], '4K': [3840, 2160] },
  '9:16': { '720p': [720, 1280], '1080p': [1080, 1920], '4K': [2160, 3840] },
  '1:1': { '720p': [720, 720], '1080p': [1080, 1080], '4K': [2160, 2160] },
};

const TOOLS = [
  {
    id: 'newspaper',
    name: 'Newspaper Mockup Video',
    description: 'Generates fake newspaper article pages cycling through styled templates (NYT, Guardian, Le Monde, etc.) with a highlighted keyword. Supports zoom/pan animations, vignette, and custom styling.',
    formats: ['mp4'],
    params: {
      keyword: { type: 'string', default: 'SZTUKA', description: 'Keyword to highlight in the article text' },
      templates: { type: 'array', items: 'string', description: 'Template IDs to use. Available: nyt, guardian, lemonde, spiegel, verge, medium, wikipedia, washingtonpost, telegraph, zeit, elpais, gazeta, nrc, folha, sueddeutsche, larepubblica, globeandmail, corriere, liberation, abc, diewelt, irishtimes, clarin, destandaard, scmp, dagensnyheter, techcrunch, wired, arstechnica, zeitmagazine, newyorker, econtwitter, buzzfeed, brutalist, meridian, hackernews, renaissance, terminal, paper' },
      format: { type: 'string', enum: ['16:9', '9:16', '1:1'], default: '16:9', description: 'Aspect ratio' },
      resolution: { type: 'string', enum: ['720p', '1080p', '4K'], default: '1080p' },
      duration: { type: 'number', default: 30, min: 3, max: 600, description: 'Video duration in seconds' },
      fps: { type: 'number', default: 30, description: 'Frames per second' },
      speed: { type: 'number', default: 800, min: 100, max: 10000, description: 'Milliseconds per slide' },
      colorAccent: { type: 'string', default: '#facc15', description: 'Highlight color (hex)' },
      customHeadline: { type: 'string', description: 'Custom headline text (overrides random)' },
      customLead: { type: 'string', description: 'Custom first paragraph (overrides random)' },
      zoomLevel: { type: 'number', default: 2.0, min: 1.0, max: 5.0 },
      zoomOffsetX: { type: 'number', default: 0, min: -300, max: 300 },
      zoomOffsetY: { type: 'number', default: 0, min: -300, max: 300 },
      fontSizeScale: { type: 'number', default: 100, min: 80, max: 140, description: 'Font size percentage' },
      lineH: { type: 'number', default: 1.72, min: 1.0, max: 2.5 },
      vignetteOpacity: { type: 'number', default: 70, min: 0, max: 100 },
      vignetteSize: { type: 'number', default: 60, min: 20, max: 80 },
      vignetteSpread: { type: 'number', default: 70, min: 10, max: 80 },
      animationPreset: { type: 'string', enum: ['none', 'zoomIn', 'zoomOut', 'panLeft', 'panRight', 'panUp', 'panDown', 'kenBurns', 'drift', 'breathe', 'swing'], default: 'none' },
      animIntensity: { type: 'number', default: 100, min: 0, max: 300 },
    },
  },
  {
    id: 'chat',
    name: 'Fake Chat Conversation Video',
    description: 'Generates animated fake chat conversations styled as iMessage, WhatsApp, Discord, Slack, Messenger, or custom theme. Messages appear one by one with typing indicators.',
    formats: ['mp4'],
    params: {
      platform: { type: 'string', enum: ['imessage', 'whatsapp', 'discord', 'slack', 'messenger', 'custom'], default: 'imessage' },
      format: { type: 'string', enum: ['16:9', '9:16', '1:1'], default: '9:16' },
      resolution: { type: 'string', enum: ['720p', '1080p', '4K'], default: '1080p' },
      fps: { type: 'number', default: 30 },
      animSpeed: { type: 'number', default: 600, min: 0, max: 5000, description: 'Animation speed ms between messages' },
      fontScale: { type: 'number', default: 100, min: 50, max: 300 },
      hideTime: { type: 'boolean', default: false },
      contacts: {
        type: 'array',
        description: 'Contact definitions [{name, color, avatar}]. Avatar = base64 data URL or image URL (optional)',
        default: [{ name: 'Jan', color: '#007AFF' }, { name: 'Anna', color: '#34C759' }],
      },
      messages: {
        type: 'array',
        description: 'Messages [{sender: 0|1, text: string}]. Sender 0 = right side (you), 1 = left side',
        default: [
          { sender: 0, text: 'Hej, widziałeś to?' },
          { sender: 1, text: 'Co dokładnie?' },
          { sender: 0, text: 'Ten nowy film dokumentalny o sztuce' },
          { sender: 1, text: 'O tak, słyszałam o nim! Podobno świetny' },
          { sender: 0, text: 'Dokładnie, musimy go obejrzeć' },
        ],
      },
      customTheme: {
        type: 'object',
        description: 'Custom theme colors {bg, headerBg, bubbleL, bubbleR, text}. Only used when platform=custom',
        default: { bg: '#1a1a2e', headerBg: '#16213e', bubbleL: '#2a2a4a', bubbleR: '#6366f1', text: '#e4e4e7' },
      },
    },
  },
  {
    id: 'typing',
    name: 'Typing Animation Video',
    description: 'Generates a video of text being typed character-by-character with a blinking cursor. Supports themes: code editor, terminal, email composer, SMS bubble, generic.',
    formats: ['mp4'],
    params: {
      theme: { type: 'string', enum: ['editor', 'terminal', 'email', 'sms', 'generic'], default: 'editor' },
      format: { type: 'string', enum: ['16:9', '9:16', '1:1'], default: '16:9' },
      resolution: { type: 'string', enum: ['720p', '1080p', '4K'], default: '1080p' },
      fps: { type: 'number', default: 30 },
      typeSpeed: { type: 'number', default: 80, min: 20, max: 300, description: 'Milliseconds per character' },
      delSpeed: { type: 'number', default: 40, min: 10, max: 200 },
      fontSize: { type: 'number', default: 20, min: 10, max: 40 },
      bgColor: { type: 'string', default: '#1e1e2e' },
      textColor: { type: 'string', default: '#cdd6f4' },
      cursorColor: { type: 'string', default: '#f5e0dc' },
      startDelay: { type: 'number', default: 500, min: 0, max: 3000 },
      endDelay: { type: 'number', default: 1500, min: 0, max: 5000 },
      cursorBlink: { type: 'boolean', default: true },
      sequences: {
        type: 'array',
        description: 'Sequence of actions [{action: "type"|"delete"|"pause"|"newline", text?, count?, duration?}]',
        default: [
          { action: 'type', text: 'const video = await generate();' },
          { action: 'pause', duration: 500 },
          { action: 'newline' },
          { action: 'type', text: 'console.log(video);' },
        ],
      },
      title: { type: 'string', default: 'untitled.txt', description: 'Editor/terminal title bar text' },
      prompt: { type: 'string', default: 'user@machine:~$', description: 'Terminal prompt' },
    },
  },
  {
    id: 'chart',
    name: 'Animated Chart Video',
    description: 'Renders animated charts: bar chart, line chart, donut/pie, animated counter, or gauge meter. Full customization of colors, animation timing, and styling.',
    formats: ['mp4'],
    params: {
      chartType: { type: 'string', enum: ['bar', 'line', 'pie', 'counter', 'gauge'], default: 'bar' },
      format: { type: 'string', enum: ['16:9', '9:16', '1:1'], default: '16:9' },
      resolution: { type: 'string', enum: ['720p', '1080p', '4K'], default: '1080p' },
      fps: { type: 'number', default: 30 },
      data: {
        type: 'array',
        description: 'Chart data [{label, value}]',
        default: [
          { label: 'Warszawa', value: 1790 },
          { label: 'Kraków', value: 1420 },
          { label: 'Wrocław', value: 1280 },
          { label: 'Gdańsk', value: 980 },
          { label: 'Poznań', value: 860 },
        ],
      },
      title: { type: 'string', default: '' },
      subtitle: { type: 'string', default: '' },
      palette: { type: 'string', enum: ['vivid', 'warm', 'cool', 'pastel', 'mono'], default: 'vivid' },
      bgColor: { type: 'string', default: '#1a1a2e' },
      textColor: { type: 'string', default: '#e4e4e7' },
      fontSize: { type: 'number', default: 32, min: 16, max: 64 },
      animDuration: { type: 'number', default: 3, min: 0.5, max: 10, description: 'Animation duration in seconds' },
      stagger: { type: 'number', default: 0.08, min: 0, max: 0.3 },
      easing: { type: 'string', enum: ['linear', 'easeInOut', 'easeOut', 'easeIn', 'bounce', 'spring'], default: 'easeOut' },
      barRadius: { type: 'number', default: 6, min: 0, max: 20, description: 'Bar chart only' },
      lineWidth: { type: 'number', default: 3, min: 1, max: 8, description: 'Line chart only' },
      lineSmooth: { type: 'boolean', default: true },
      donutHole: { type: 'number', default: 0.6, min: 0, max: 0.9, description: 'Pie chart only' },
      counterFrom: { type: 'number', default: 0, description: 'Counter only' },
      counterTo: { type: 'number', default: 1000000, description: 'Counter only' },
      counterPrefix: { type: 'string', default: '' },
      counterSuffix: { type: 'string', default: '' },
      counterDecimals: { type: 'number', default: 0 },
      gaugeValue: { type: 'number', default: 72, min: 0, max: 100 },
      gaugeLabel: { type: 'string', default: 'Performance' },
      showLabels: { type: 'boolean', default: true },
      showValues: { type: 'boolean', default: true },
      showGrid: { type: 'boolean', default: true },
      showLegend: { type: 'boolean', default: true },
    },
  },
  {
    id: 'map',
    name: 'Map Travel Route Video',
    description: 'Creates animated map travel videos showing a vehicle moving along a route between geographic waypoints. Supports plane, car, ship, train. Car/train uses real road routing via OSRM.',
    formats: ['mp4'],
    params: {
      waypoints: {
        type: 'array',
        description: 'Route waypoints [{lat, lng, name}]. At least 2 required.',
        default: [
          { lat: 52.2297, lng: 21.0122, name: 'Warsaw' },
          { lat: 48.8566, lng: 2.3522, name: 'Paris' },
        ],
      },
      transportType: { type: 'string', enum: ['plane', 'car', 'ship', 'train'], default: 'plane' },
      mapStyle: { type: 'string', enum: ['dark', 'light', 'topo'], default: 'dark' },
      cameraMode: { type: 'string', enum: ['follow', 'overview'], default: 'follow' },
      format: { type: 'string', enum: ['16:9', '9:16', '1:1'], default: '16:9' },
      resolution: { type: 'string', enum: ['720p', '1080p', '4K'], default: '1080p' },
      fps: { type: 'number', default: 30 },
      routeColor: { type: 'string', default: '#6366f1' },
      routeWidth: { type: 'number', default: 4, min: 1, max: 10 },
      animDuration: { type: 'number', default: 5, min: 1, max: 30, description: 'Animation duration in seconds' },
      zoom: { type: 'number', default: 5, min: 2, max: 18 },
      easing: { type: 'boolean', default: true },
      showLabels: { type: 'boolean', default: true },
      segmentColors: { type: 'array', description: 'Colors for each route leg', default: ['#6366f1', '#f43f5e', '#22c55e', '#f59e0b', '#06b6d4', '#a855f7', '#ec4899', '#14b8a6'] },
    },
  },
  {
    id: 'notification',
    name: 'Phone Notification Stack Video',
    description: 'Generates animated phone notification sequences (iOS/Android) sliding in and stacking. 15 preset app types (Instagram, X, TikTok, WhatsApp, etc.) or fully custom. Supports alpha channel export (MOV, WebM).',
    formats: ['mp4', 'mov', 'webm'],
    params: {
      theme: { type: 'string', enum: ['ios', 'android', 'custom'], default: 'ios' },
      preset: { type: 'string', enum: ['ig-follow', 'ig-like', 'ig-comment', 'ig-dm', 'x-rt', 'x-like', 'x-mention', 'tt-follow', 'sms', 'whatsapp', 'email', 'snapchat', 'telegram', 'youtube', 'linkedin'], description: 'Prepend a preset notification' },
      notifications: {
        type: 'array',
        description: 'Notifications [{appName, title, message, accentColor}]',
        default: [
          { appName: 'Instagram', title: 'Jan Kowalski', message: 'zaobserwował Cię!', accentColor: '#E1306C' },
          { appName: 'X', title: '@user123', message: 'podbił Twój tweet', accentColor: '#1DA1F2' },
          { appName: 'WhatsApp', title: 'Kamil', message: 'Grasz dziś wieczorem?', accentColor: '#25D366' },
        ],
      },
      format: { type: 'string', enum: ['16:9', '9:16', '1:1'], default: '9:16' },
      resolution: { type: 'string', enum: ['720p', '1080p', '4K'], default: '1080p' },
      fps: { type: 'number', default: 30 },
      slideDirection: { type: 'string', enum: ['top', 'bottom'], default: 'top' },
      stackPosition: { type: 'string', enum: ['left', 'right', 'center'], default: 'right' },
      animSpeed: { type: 'number', default: 800, min: 200, max: 2000 },
      maxVisible: { type: 'number', default: 5, min: 2, max: 12 },
      stackOverlap: { type: 'number', default: 0, min: 0, max: 80 },
      fadeOut: { type: 'boolean', default: true },
      bgMode: { type: 'string', enum: ['white', 'green', 'black'], default: 'white', description: 'Background mode. Green = chroma key for compositing' },
      customBg: { type: 'string', default: '#f2f2f2', description: 'Custom theme background (theme=custom)' },
      customBorder: { type: 'string', default: '#e5e5e5', description: 'Custom theme border color' },
      customTitle: { type: 'string', default: '#000', description: 'Custom theme title color' },
      customText: { type: 'string', default: '#666', description: 'Custom theme text color' },
      customRadius: { type: 'number', default: 16, min: 0, max: 40, description: 'Custom theme border radius' },
    },
  },
];

function getResolution(format, resolution) {
  return RESOLUTIONS[format] && RESOLUTIONS[format][resolution]
    ? RESOLUTIONS[format][resolution]
    : [1920, 1080];
}

function listTools() {
  return {
    tools: TOOLS.map((t) => ({
      id: t.id,
      name: t.name,
      description: t.description,
      formats: t.formats,
      params: t.params,
    })),
  };
}

module.exports = { TOOLS, RESOLUTIONS, getResolution, listTools };
